# Generated by Django 2.0 on 2023-03-18 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentmodel',
            options={'permissions': (('view_departmentmodel', 'Can view department model'),)},
        ),
    ]
